# Generated by Django 4.1.2 on 2022-10-09 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_car_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='title',
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
