# Generated by Django 4.1.2 on 2022-10-09 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_car_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='title',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
