# Generated by Django 4.1.2 on 2022-10-09 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_destacados_caracteristicas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caracteristicas',
            name='description',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
